### ISSUE TITLE
Roadmap to Specification

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MediatorManager#1]
### Collaboration

- [ ] Read [Introduction to Git and GitHub](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/Introduction2Git/Introduction2Git.md)
- [ ] Read [Workflow for Contributing](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/WorkflowForContributing/WorkflowForContributing.md)
- [ ] Read [GitFlow Workflow](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/GitFlowWorkflow/GitFlowWorkflow.md)
- #002
- #003
- #004
- #005
- [ ] Make yourself familiar with the [Basic Syntax of Markdown](https://www.markdownguide.org/basic-syntax/)
- [ ] Read [Formulating Issues](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md)
- [ ] Read [Formulating Commit and Merge Request Messages](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingCommitMessages/FormulatingCommitMessages.md)
- [ ] Read [Management of Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/ConflictManagement/ConflictManagement.md)
- [ ] Read [Avoiding Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/AvoidingConflicts/AvoidingConflicts.md)
- #006
